export { default as Homepage } from '../pages/home/Homepage'
export { default as Clubs } from '../pages/clubs/Clubs'
export { default as Discover } from '../pages/discover/Discover'
export { default as Download } from '../pages/download/Download'
export { default as Clubdetails } from '../pages/clubs/Clubdetails'
